schema_version: 7.0
type: producer
identifier: alive
title: Alive Animation
version: 3
copyright: Copyright (C) 2011-2025 Meltytech, LLC
license: LGPL
language: en
creator: Sanjay
tags:
  - Video
description: >
  Alive Animation
notes: >
  Alive Animation
bugs:
  - Everything is bug at present :)
parameters:
  - identifier: resource
    title: Resource
    type: string
    description: Identifier for the custom resource
    readonly: no
    required: yes
    mutable: no
  - identifier: length
    title: Length
    type: integer
    description: Duration in frames
    readonly: no
    default: 100
    mutable: yes
    widget: spinner
